[package]
name = "dirkdb"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
dialoguer = "0.12.0"
indexmap = "2.11.1"
nanoid = "0.4.0"
nom = "8.0.0"
regex = "1.11.1"
serde = "1.0.219"
thiserror = "2.0.16"
uuid = "1.18.1"
